rep_site:
    resource: "@RepSiteBundle/Resources/config/routing.yml"
    prefix:   /
    
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api
  
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  
#hwi_oauth_security:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: login
#
#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix: /login
#
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google