# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.provider.oauth:
        class: Rep\SiteBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]
    hwi_oauth.registration.form:
        class: Rep\SiteBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    