<?php

namespace Rep\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArtistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistaRepository extends EntityRepository
{
    
    public function listarTodos(){
        $qb = $this->createQueryBuilder('a')
                ->select('a')
                ->addOrderBy('a.nome');

        return $qb->getQuery()->getResult();
    }
    
}
