<?php

namespace Rep\SiteBundle\Entity\Repository;

/**
 * BlocoRepertorioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocoRepertorioRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('br')
                ->select('br.id', 'br.nome', 'r.id AS repertorio', 'br.status', 
                        'br.ultimaAlteracao AS ultima_alteracao', 'br.ordem')
                ->distinct()
                ->leftJoin("RepSiteBundle:Repertorio", "r", "WITH", "r.id = br.repertorio")
                ->where("br.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('br.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
