<?php

namespace Rep\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoCasaRepository extends EntityRepository
{
    
    public function listarTodosPorCasa($slug){
        $qb = $this->createQueryBuilder('cc')
                ->select('c')
                ->leftJoin("RepSiteBundle:Contato", 'c', 'WITH', 'c.id = cc.contato')
                ->leftJoin("RepSiteBundle:Casa", 'ca', 'WITH', 'ca.id = ca.casa')
                ->andWhere('ca.slug = :casa')
                ->andWhere('cc.status = 0')
                ->setParameter(':casa', $slug)
                ->addOrderBy('c.nome');

        return $qb->getQuery()->getResult();
    }
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('cc')
                ->select('cc.id', 'cc.observacao', 'c.id AS contato', 'ca.id AS casa', 'cc.status', 
                        'cc.ultimaAlteracao AS ultima_alteracao', 'cc.cargo')
                ->distinct()
                ->leftJoin("RepSiteBundle:Contato", "c", "WITH", "c.id = cc.contato")
                ->leftJoin("RepSiteBundle:Casa", "ca", "WITH", "ca.id = cc.casa")
                ->where("cc.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('cc.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
