<?php

namespace Rep\SiteBundle\Entity\Repository;

/**
 * EstiloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstiloRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodos(){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->addOrderBy('e.nome');

        return $qb->getQuery()->getResult();
    }
    
    public function listarTodosPorProjeto($slug, $status){
        
        if($status > -1){
            $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->innerJoin("RepSiteBundle:Musica", 'm', 'WITH', 'm.estilo = e.id')
                ->innerJoin("RepSiteBundle:MusicaProjeto", 'mp', 'WITH', 'mp.musica = m.id')
                ->innerJoin("RepSiteBundle:Projeto", 'p', 'WITH', 'p.id = mp.projeto')
                ->where('p.slug = :projeto')
                ->andWhere('e.status = :status')
                ->andWhere('mp.status = 0')
                ->setParameter(':projeto', $slug)
                ->setParameter(':status', $status)
                ->addOrderBy('m.nome');
        } else{
            $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->innerJoin("RepSiteBundle:Musica", 'm', 'WITH', 'm.estilo = e.id')
                ->innerJoin("RepSiteBundle:MusicaProjeto", 'mp', 'WITH', 'mp.musica = m.id')
                ->innerJoin("RepSiteBundle:Projeto", 'p', 'WITH', 'p.id = mp.projeto')
                ->where('p.slug = :projeto')
                ->andWhere('e.status <> 2')
                ->andWhere('mp.status = 0')
                ->setParameter(':projeto', $slug)
                ->addOrderBy('m.nome');
        }
        
        

        return $qb->getQuery()->getResult();
    }
    
}
