<?php

namespace Rep\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository
{
    
    function listarProximosEventos(){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->where("e.data >= :dataAtual")
                ->setParameter('dataAtual', new \DateTime())
                ->addOrderBy('e.data');
        
        return $qb->getQuery()->getResult();
    }
    
    function listarTodos(){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->addOrderBy('e.data', 'DESC');
        
        return $qb->getQuery()->getResult();
    }
    
    function listarTodosAtivos(){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->where('e.status != 2')
                ->addOrderBy('e.data');
        
        return $qb->getQuery()->getResult();
    }
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('e')
                ->select('e.id, e.nome, e.data, e.status, te.id AS tipo_evento, e.ultimaAlteracao AS ultima_alteracao, e.slug')
                ->distinct()
                ->leftJoin("RepSiteBundle:TipoEvento", "te", "WITH", "te.id = e.tipoEvento")
                ->where("e.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('e.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    function listarTodosPorDia($data){
        
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->where('e.data BETWEEN :dataInicio AND :dataFim')
                ->addOrderBy('e.data')
                ->setParameter('dataInicio', $data.' 00:00:00')
                ->setParameter('dataFim', $data.' 23:59:59');
        
        return $qb->getQuery()->getResult();
    }
    
    function listarTodosPassadosPorProjeto($tipo, $id_projeto, $limite){
        
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->innerJoin("RepSiteBundle:TipoEvento", 'te', 'WITH', 'te.id = e.tipoEvento')
                ->where("te.nome = :tipo")
                ->andWhere("e.projeto = :projeto")
                ->andWhere('e.data <= :data')
                ->addOrderBy('e.data', 'DESC')
                ->setParameter('projeto', $id_projeto)
                ->setParameter('tipo', $tipo)
                ->setParameter('data', new \DateTime())
                ;
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
    }
    
    function listarTodosFuturosPorProjeto($tipo, $id_projeto, $limite){
        
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->innerJoin("RepSiteBundle:TipoEvento", 'te', 'WITH', 'te.id = e.tipoEvento')
                ->where("te.nome = :tipo")
                ->andWhere("e.projeto = :projeto")
                ->andWhere('e.data > :data')
                ->addOrderBy('e.data')
                ->setParameter('projeto', $id_projeto)
                ->setParameter('tipo', $tipo)
                ->setParameter('data', new \DateTime())
                ;
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
    }
    
}
