<?php

namespace Rep\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArtistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogEntryRepository extends Gedmo\Loggable\Entity\Repository\LogEntryRepository
{
    
    public function listarTodos(){
        $qb = $this->createQueryBuilder('l')
                ->select('l')
                ->addOrderBy('l.action');

        return $qb->getQuery()->getResult();
    }
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('l')
//                ->select('b.id, b.nome, b.status, l.id AS local')
                ->select('l.id')
                ->distinct()
//                ->leftJoin("CircularSiteBundle:Local", "l", "WITH", "l.id = b.local")
                ->where("a.logged_at > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('l.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
