<?php

namespace Rep\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicaEventoRepository extends EntityRepository
{
    
    function listaMusicasAtivasAusentesNoEvento($id_evento){
        $qb = $this->createQueryBuilder('me');
        
        $musicasEvento = $qb->select('IDENTITY(me.musica)')
          ->where('me.evento = '.$id_evento)
          ->andWhere('me.status = 0')
          ->getQuery()
          ->getResult();
        
        if(sizeof($musicasEvento) > 0){
            return $qb->select('m1')
            ->distinct()
            ->from("RepSiteBundle:Musica", "m1")
            ->where('m1.id NOT IN (:musicasEvento)')
                    ->andWhere('m1.status = 0')
                    ->setParameter('musicasEvento', $musicasEvento)
                    ->addOrderBy('m1.nome')
            ->getQuery()
            ->getResult();
        } else{
            return $qb->select('m')
            ->distinct()
            ->from("RepSiteBundle:Musica", "m")
                    ->where('m.id NOT IN (0)')
                    ->andWhere('m.status = 0')
                    ->addOrderBy('m.nome')
            ->getQuery()
            ->getResult();
        }
                
        
    }
    
    public function invalidaTodasMusicasEvento($id_evento){
        
        $qb = $this->createQueryBuilder('me')
                ->update("RepSiteBundle:MusicaEvento", 'me')
                ->set('me.status', 2)
                ->set('me.ultimaAlteracao', ':now')
                ->where('me.evento = :id_evento')
                ->andWhere('me.status != 2')
                ->setParameter('now', new \DateTime())
                ->setParameter('id_evento', $id_evento);

        $qb->getQuery()->getResult();
        
        return true;
        
    }
    
}
