<?php

namespace Rep\SiteBundle\Entity\Repository;

/**
 * MusicaBlocoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicaBlocoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('mb')
                ->select('mb.id', 'mb.observacao', 'm.id AS musica', 'b.id AS bloco_repertorio', 'mb.status', 
                        'mb.ultimaAlteracao AS ultima_alteracao', 'mb.ordem')
                ->distinct()
                ->leftJoin("RepSiteBundle:Musica", "m", "WITH", "m.id = mb.musica")
                ->leftJoin("RepSiteBundle:BlocoRepertorio", "b", "WITH", "b.id = mb.bloco_repertorio")
                ->where("mb.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('mb.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
