<?php

namespace Rep\SiteBundle\Entity\Repository;

/**
 * MusicaProjetoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicaProjetoRepository extends \Doctrine\ORM\EntityRepository
{
}
