<?php

namespace Rep\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MusicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicaRepository extends EntityRepository
{
    
    public function listarTodas(){
        $qb = $this->createQueryBuilder('m')
                ->select('m')
                ->addOrderBy('m.nome');

        return $qb->getQuery()->getResult();
    }
    
}
