<?php

namespace Rep\SiteBundle\Entity\Repository;

/**
 * ProjetoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetoRepository extends \Doctrine\ORM\EntityRepository
{
}
