<?php

namespace Rep\SiteBundle\Entity\Repository;

/**
 * TempoMusicaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempoMusicaEventoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodosREST($limite = null, $dataUltimoAcesso){
        $qb = $this->createQueryBuilder('tme')
                ->select('tme.id', 'tme.tempo', 'me.id AS musica_evento', 'tme.status', 'tme.audio',
                        'tme.ultimaAlteracao AS ultima_alteracao')
                ->distinct()
                ->leftJoin("RepSiteBundle:MusicaEvento", "me", "WITH", "me.id = tme.musicaEvento")
                ->where("tme.ultimaAlteracao > :ultimaAlteracao")
                ->setParameter('ultimaAlteracao', $dataUltimoAcesso)
                ->addOrderBy('tme.id');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
