#pais : 
#  type: rest
#  resource:     "CircularSiteBundle:PaisRest"
#  name_prefix:  api_

rep_api_get_token:
    pattern: /token
    defaults: {_controller: RepSiteBundle:RepRest:getToken}
  
rep_api_get_dados:
    pattern: /recebe-dados/{hash}/{data}
    defaults: {_controller: RepSiteBundle:RepRest:getDados}
    
rep_api_set_dados:
    pattern: /envia-dados/{hash}/{data}
    defaults: {_controller: RepSiteBundle:RepRest:setDados}
    
rep_api_valida_token:
    pattern: /valida-token
    defaults: {_controller: RepSiteBundle:RepRest:validaToken}