rep_site_homepage:
    pattern:  /
    defaults: { _controller: RepSiteBundle:Page:index }
    
rep_site_popula_tom:
    pattern:  /popula-tom
    defaults: { _controller: RepSiteBundle:Page:populaTom }
    
rep_site_backup:
    pattern:  /backup
    defaults: { _controller: RepSiteBundle:Page:backup }

########################################################################

rep_site_artistas:
    path:     /artistas
    defaults: { _controller: RepSiteBundle:Page:artistas }
    
rep_site_artistas_cadastra:
    pattern:     /artistas/cadastra/{id_artista}
    defaults: { _controller: RepSiteBundle:Artista:cadastrar, id_artista: -1 }
    requirements:
        _method: POST

rep_site_artistas_form:
    pattern: /artistas/form/{id_artista}
    defaults: {_controller: RepSiteBundle:Artista:form, id_artista: -1}
    
rep_site_artistas_musicas:
    pattern: /artistas/musicas/{id_artista}
    defaults: {_controller: RepSiteBundle:Artista:musicas, id_artista: -1}

rep_site_artistas_form_novo:
    pattern: /artistas/form-novo/{id_artista}
    defaults: {_controller: RepSiteBundle:Artista:formNovo, id_artista: -1}
    
rep_site_artistas_cadastra_novo:
    pattern:     /artistas/cadastra-novo/{id_artista}
    defaults: { _controller: RepSiteBundle:Artista:cadastrarNovo, id_artista: -1 }
    requirements:
        _method: POST
    
########################################################################

rep_site_musicas:
    path:     /musicas
    defaults: { _controller: RepSiteBundle:Page:musicas }
    
rep_site_musicas_cadastra:
    pattern:     /musicas/cadastra/{id_musica}
    defaults: { _controller: RepSiteBundle:Musica:cadastrar, id_musica: -1 }
    requirements:
        _method: POST

rep_site_musicas_form:
    pattern: /musicas/form/{id_musica}
    defaults: {_controller: RepSiteBundle:Musica:form, id_musica: -1}
    
rep_site_musicas_detalhes:
    pattern: /{artista}/musicas/{slug}/detalhes
    defaults: {_controller: RepSiteBundle:Musica:detalhes, artista: '', slug: '', id: -1 }
    
rep_site_musicas_detalhes_por_id:
    pattern: /musicas/detalhes/{id}
    defaults: {_controller: RepSiteBundle:Musica:detalhes, artista: '', slug: '', id: -1 }    
    
########################################################################

rep_site_eventos:
    path:     /eventos
    defaults: { _controller: RepSiteBundle:Page:eventos }
    
rep_site_eventos_cadastra:
    pattern:     /eventos/cadastra/{id_evento}
    defaults: { _controller: RepSiteBundle:Evento:cadastrar, id_evento: -1 }
    requirements:
        _method: POST

rep_site_eventos_form:
    pattern: /eventos/form/{id_evento}
    defaults: {_controller: RepSiteBundle:Evento:form, id_evento: -1}
    
rep_site_eventos_data:
    path:     /eventos/{data}
    defaults: { _controller: RepSiteBundle:Evento:eventosData, data: '' }
    
########################################################################

rep_site_tipos_evento:
    path:     /tipos-evento
    defaults: { _controller: RepSiteBundle:Page:tiposEvento }
    
rep_site_tipos_evento_cadastra:
    pattern:     /tipos-evento/cadastra/{id_tipo_evento}
    defaults: { _controller: RepSiteBundle:TipoEvento:cadastrar, id_tipo_evento: -1 }
    requirements:
        _method: POST

rep_site_tipos_evento_form:
    pattern: /tipos-evento/form/{id_tipo_evento}
    defaults: {_controller: RepSiteBundle:TipoEvento:form, id_tipo_evento: -1}
    
########################################################################

rep_site_musicas_evento:
    path:     /musicas-evento/{slug}
    defaults: { _controller: RepSiteBundle:MusicaEvento:musicasEvento, slug: -1 }

rep_site_atualiza_musicas_evento:
    path:     /musicas-evento/{id_evento}/atualiza
    defaults: { _controller: RepSiteBundle:MusicaEvento:atualizaMusicasEvento, id_evento: -1 }
    
rep_site_form_cadastra_musicas_evento:
    path:     /musicas-evento/{id_evento}/cadastra/form
    defaults: { _controller: RepSiteBundle:MusicaEvento:formCadastraMusica, id_evento: -1 }
    
rep_site_cadastra_musicas_evento:
    path:     /musicas-evento/{id_evento}/cadastra
    defaults: { _controller: RepSiteBundle:MusicaEvento:cadastraMusica, id_evento: -1 }
    
rep_site_tabela_musicas_evento:
    path:     /musicas-evento/{id_evento}/repertorio
    defaults: { _controller: RepSiteBundle:MusicaEvento:carregaRepertorio, id_evento: -1 }
    
rep_site_remove_musica_evento:
    path:     /musicas-evento/{id_evento}/repertorio/remove/{id_musica}
    defaults: { _controller: RepSiteBundle:MusicaEvento:removeMusicaEvento, id_evento: -1, id_musica: -1 }
    
rep_site_form_cadastra_ordem_musicas_evento:
    path:     /musicas-evento/{id_evento}/repertorio/ordem
    defaults: { _controller: RepSiteBundle:MusicaEvento:ordemMusicaEvento, id_evento: -1 }
    
rep_site_cadastra_intervalo_evento:
    path:     /musicas-evento/{id_evento}/cadastra/intervalo
    defaults: { _controller: RepSiteBundle:MusicaEvento:cadastraIntervalo, id_evento: -1 }
    
rep_site_gera_pdf_repertorio_evento:
    path:     /musicas-evento/{slug}/repertorio/pdf
    defaults: { _controller: RepSiteBundle:MusicaEvento:geraPdf, slug: '' }

########################################################################
    
rep_site_tabela_comentarios_evento:
    path:     /comentarios-evento/{id_evento}
    defaults: { _controller: RepSiteBundle:ComentarioEvento:carregaComentarios, id_evento: -1 }
    
rep_site_form_cadastra_comentario_evento:
    path:     /comentarios-evento/{id_evento}/cadastra/form
    defaults: { _controller: RepSiteBundle:ComentarioEvento:cadastraComentario, id_evento: -1 }
    
########################################################################

rep_site_projetos:
    path:     /projetos
    defaults: { _controller: RepSiteBundle:Page:projetos }
    
rep_site_projetos_cadastra:
    pattern:     /projetos/cadastra/{id_projeto}
    defaults: { _controller: RepSiteBundle:Projeto:cadastrar, id_projeto: -1 }
    requirements:
        _method: POST

rep_site_projetos_form:
    pattern: /projetos/form/{id_projeto}
    defaults: {_controller: RepSiteBundle:Projeto:form, id_projeto: -1}
    
rep_site_projetos_muda:
    pattern: /projetos/muda
    defaults: {_controller: RepSiteBundle:Projeto:muda}
    
########################################################################

rep_site_musicas_projetos:
    path:     /projetos/{projeto}/musicas
    defaults: { _controller: RepSiteBundle:Page:musicasProjetos, projeto: '' }
    
rep_site_musicas_projetos_cadastra:
    pattern:     /musicas-projetos/cadastra/{id_musica_projeto}
    defaults: { _controller: RepSiteBundle:MusicaProjeto:cadastrar, id_musica_projeto: -1 }
    requirements:
        _method: POST
        
rep_site_musicas_projetos_form:
    pattern: /musicas-projetos/form/{id_musica_projeto}
    defaults: {_controller: RepSiteBundle:MusicaProjeto:form, id_musica_projeto: -1}
    
rep_site_atualiza_musicas_projeto:
    path:     /musicas-projeto/{id_projeto}/atualiza
    defaults: { _controller: RepSiteBundle:MusicaProjeto:atualizaMusicasProjeto, id_projeto: -1 }
    
rep_site_form_cadastra_musicas_projeto:
    path:     /musicas-projeto/{id_projeto}/cadastra/form
    defaults: { _controller: RepSiteBundle:MusicaProjeto:formCadastraMusica, id_projeto: -1 }
    
rep_site_cadastra_musicas_projeto:
    path:     /musicas-projeto/{id_projeto}/cadastra
    defaults: { _controller: RepSiteBundle:MusicaProjeto:cadastraMusica, id_projeto: -1 }
    
rep_site_tabela_musicas_projeto:
    path:     /musicas-projeto/{id_projeto}/repertorio/{status}
    defaults: { _controller: RepSiteBundle:MusicaProjeto:carregaRepertorio, id_projeto: -1, status: -1 }
    
rep_site_remove_musica_projeto:
    path:     /musicas-projeto/{id_projeto}/repertorio/remove/{id_musica}
    defaults: { _controller: RepSiteBundle:MusicaProjeto:removeMusicaProjeto, id_projeto: -1, id_musica: -1 }
    
rep_site_form_cadastra_novas_musicas_projeto:
    path:     /musicas-projeto/{id_projeto}/cadastra/nova/form
    defaults: { _controller: RepSiteBundle:MusicaProjeto:formCadastraMusicaNova, id_projeto: -1 }
    
rep_site_musicas_projetos_novas_cadastra:
    pattern:     /musicas-projeto/cadastra/{id_projeto}
    defaults: { _controller: RepSiteBundle:MusicaProjeto:cadastrarNova, id_projeto: -1 }
    requirements:
        _method: POST
        
########################################################################

rep_site_estilos:
    path:     /estilos
    defaults: { _controller: RepSiteBundle:Page:estilos }
    
rep_site_estilos_cadastra:
    pattern:     /estilos/cadastra/{id_estilo}
    defaults: { _controller: RepSiteBundle:Estilo:cadastrar, id_estilo: -1 }
    requirements:
        _method: POST

rep_site_estilos_form:
    pattern: /estilos/form/{id_estilo}
    defaults: {_controller: RepSiteBundle:Estilo:form, id_estilo: -1}
    
rep_site_estilos_musicas:
    pattern: /estilos/musicas/{id_estilo}
    defaults: {_controller: RepSiteBundle:Estilo:musicas, id_estilo: -1}

rep_site_estilos_form_novo:
    pattern: /estilos/form-novo/{id_estilo}
    defaults: {_controller: RepSiteBundle:Estilo:formNovo, id_estilo: -1}
    
rep_site_estilos_cadastra_novo:
    pattern:     /estilos/cadastra-novo/{id_estilo}
    defaults: { _controller: RepSiteBundle:Estilo:cadastrarNovo, id_estilo: -1 }
    requirements:
        _method: POST
    
########################################################################

rep_site_repertorios:
    path:     /repertorios
    defaults: { _controller: RepSiteBundle:Page:repertorios }
    
rep_site_repertorios_cadastra:
    pattern:     /repertorios/cadastra/{id_projeto}/{id_repertorio}
    defaults: { _controller: RepSiteBundle:Repertorio:cadastrar, id_projeto: -1, id_repertorio: -1 }
    requirements:
        _method: POST

rep_site_repertorios_form:
    pattern: /repertorios-teste/form/{id_projeto}/{id_repertorio}
    defaults: {_controller: RepSiteBundle:Repertorio:form, id_projeto: -1, id_repertorio: -1}
    
########################################################################

rep_site_musicas_repertorio:
    path:     /musicas-repertorio/{slug}
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:musicasRepertorio, slug: -1 }

rep_site_atualiza_musicas_repertorio:
    path:     /musicas-repertorio/{id_repertorio}/atualiza
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:atualizaMusicasRepertorio, id_repertorio: -1 }
    
rep_site_form_cadastra_musicas_repertorio:
    path:     /musicas-repertorio/{id_repertorio}/cadastra/form
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:formCadastraMusica, id_repertorio: -1 }
    
rep_site_cadastra_musicas_repertorio:
    path:     /musicas-repertorio/{id_repertorio}/cadastra
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:cadastraMusica, id_repertorio: -1 }
    
rep_site_tabela_musicas_repertorio:
    path:     /musicas-repertorio/{id_repertorio}/repertorio
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:carregaRepertorio, id_repertorio: -1 }
    
rep_site_remove_musica_repertorio:
    path:     /musicas-repertorio/{id_repertorio}/repertorio/remove/{id_musica}
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:removeMusicaRepertorio, id_repertorio: -1, id_musica: -1 }
    
rep_site_form_cadastra_ordem_musicas_repertorio:
    path:     /musicas-repertorio/{id_repertorio}/repertorio/ordem
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:ordemMusicaRepertorio, id_repertorio: -1 }
    
rep_site_gera_pdf_repertorio:
    path:     /musicas-repertorio/{slug}/repertorio/pdf
    defaults: { _controller: RepSiteBundle:MusicaRepertorio:geraPdf, slug: '' }

########################################################################