parameters:
#    rep_site.example.class: Rep\SiteBundle\Example

services:
#    rep_site.example:
#        class: %rep_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    app.form.type.evento:
            class: Rep\SiteBundle\Form\Type\EventoType
            arguments: [Rep\SiteBundle\Entity\Evento]
            tags:
                - { name: form.type }